# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoryBoardTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StoryBoardTest
  pod “Alamofire”
  pod "SwiftyJSON"

  target 'StoryBoardTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoryBoardTestUITests' do
    # Pods for testing
  end

end
